version: "3.7"

services:

  mysql:
    image: mysql:5.7
    command: "--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=alibaba
      - MYSQL_DATABASE=tiendatax
    volumes:
      - ./.data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    labels:
      - "traefik.http.routers.pma.rule=Host(`pma-tiendatax.local.tax.com`)"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    ports:
      - "8080:80"

  site:
    build: .
    #env_file:
    #  - ./backend/.env
    labels:
      - "traefik.http.routers.api.rule=Host(`site-tiendatax.local.tax.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    volumes:
      - .:/var/www/api

  traefik:
    image: traefik:v2.3
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
